---
- name: Add hashicorp apt key.
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    validate_certs: true

- name: Add hashicorp repo into sources list
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
    state: present

- name: Install common packages
  apt:
    name:
      - "ssl-cert"
      - "consul={{ consul_version }}"
    state: present

- name: Pin consul release
  copy:
    mode: 0640
    dest: /etc/apt/preferences.d/consul
    content: |
      Package: consul
      Pin: version {{ consul_version }}
      Pin-Priority: 1002

- name: Add consul user to ssl-cert group
  user:
    name: consul
    groups: ssl-cert
    append: true

- name: Check directories exist
  file:
    path: "{{ _current_dir }}"
    owner: consul
    group: consul
    state: directory
    mode: 0700
  loop: "{{ __consul_expected_directories }}"
  loop_control:
    loop_var: _current_dir

- name: Common private ssl directory
  file:
    path: "{{ __consul_tls_dir }}"
    owner: root
    group: ssl-cert
    state: directory
    mode: 0750
