---
collections:
  - name: community.docker
  - name: community.crypto
  - name: community.general
    version: 4.5.0
  - name: ansible.utils
  - name: ansible.netcommon
  - name: ansible.posix
  - name: rtnp.galaxie_clans

roles:
  - name: cloudalchemy.grafana
  - name: cloudalchemy.prometheus
  - name: cloudalchemy.node_exporter
