__consul_is_master: >-
  {{
    consul_inventory_masters_group is defined
    and consul_inventory_masters_group | length > 0
    and inventory_hostname in groups[consul_inventory_masters_group]
  }}

__consul_is_minion: "{{ not __consul_is_master }}"

__consul_tls_dir: "/etc/ssl/private"

__consul_data_dir: "/opt/consul/data"
__consul_expected_directories:
  - "{{ __consul_data_dir }}"

__consul_home: "/home/consul"

__consul_self_private_key: "{{ __consul_tls_dir }}/self.cert.key"
__consul_self_certificate: "{{ __consul_tls_dir }}/self.fullchain.cert.pem"
__consul_vault_root_ca_certificate_path: "/usr/local/share/ca-certificates/vault.root_ca.crt"

__consul_encrypt_key_local_path: "{{ consul_local_secrets_dir }}/consul.encrypt_key"
__consul_encrypt_key: >-
  {{ lookup('file', __consul_encrypt_key_local_path) }}

__consul_acl_bootstrapped: false

