---
- name: First node init
  include_tasks: "vault_init.yml"
  run_once: true

- include_tasks: "vault_status.yml"
  loop: "{{ range(0, 10)|list }}"
  when:
    - inventory_hostname == groups[vault_inventory_masters_group][0]
    - _vault_status is not defined or not _vault_status.initialized

- name: Set unseal target
  set_fact:
    vault_unseal_target: "{{ [groups[vault_inventory_masters_group][0]] }}"

- name: Unseal first node
  include_tasks: vault_unseal.yml
  when: inventory_hostname == groups[vault_inventory_masters_group][0]

- include_tasks: "vault_status.yml"
  loop: "{{ range(0, 10)|list }}"
  when:
    - inventory_hostname == groups[vault_inventory_masters_group][0]
    - _vault_status is not defined or _vault_status.sealed

- set_fact:
    vault_unseal_target: "{{ groups[vault_inventory_masters_group][1:] }}"

- name: Unseal every other nodes
  include_tasks: vault_unseal.yml
  when: inventory_hostname != groups[vault_inventory_masters_group][0]
