---
- name: First node init
  include_tasks: "vault_init.yml"
  run_once: true

- name: Get vault status
  uri:
    url: "{{ __vault_api_status }}"
    return_content: yes
  register: _current_vault_status
  when:
    - inventory_hostname == groups[vault_inventory_masters_group][0]
  retries: 10
  delay: 10
  until:
    - _current_vault_status.status == 200
    - _current_vault_status.json.initialized

- name: Set unseal target
  set_fact:
    vault_unseal_target: "{{ [groups[vault_inventory_masters_group][0]] }}"

- name: Unseal first node
  include_tasks: vault_unseal.yml
  when: inventory_hostname == groups[vault_inventory_masters_group][0]

- name: Get vault status
  uri:
    url: "{{ __vault_api_status }}"
    return_content: yes
  register: _current_vault_status
  when:
    - inventory_hostname == groups[vault_inventory_masters_group][0]
  retries: 10
  delay: 10
  until:
    - _current_vault_status.status == 200
    - not _current_vault_status.json.sealed

- set_fact:
    vault_unseal_target: "{{ groups[vault_inventory_masters_group][1:] }}"

- name: Unseal every other nodes
  include_tasks: vault_unseal.yml
  when: inventory_hostname != groups[vault_inventory_masters_group][0]
