---
- name: Install
  include_tasks: install.yml
  when: __vault_is_master

- name: Start master vault services
  systemd:
    state: started
    name: vault
    daemon_reload: true
  when: __vault_is_master

- name: In-place init-unseal
  include_tasks: _inplace_init_unseal.yml
  when:
    - __vault_is_master
    - vault_unseal_method == 'in-place'

- name: Flush before leaving
  meta: flush_handlers
