---
- name: Wait for vault api
  wait_for:
    host: "{{ vault_api_address }}"
    port: "{{ vault_api_port }}"
    timeout: 120
  no_log: true

- name: Read raw vault status
  command: >-
    vault status -format json -address={{ vault_conf_api_addr }}
  register: _vault_status_results
  changed_when: false
  failed_when: _vault_status_results.rc == 1

- name: Set vault status
  set_fact:
    _vault_status: "{{ _vault_status_results.stdout | from_json }}"
