---
- include_tasks: "vault_status.yml"

- block:
    - name: Node initialization
      command: >-
        vault operator init -format json -address={{ __vault_conf_api_addr }}
      register: _vault_init_results

    - name: Store vault init keys
      copy:
        dest: "{{ vault_local_unseal_file }}"
        mode: 0600
        content: |-
          ---
          {{ _vault_init_results.stdout | from_json | to_nice_yaml }}
      become: false
      delegate_to: localhost

    - include_tasks: "vault_status.yml"
  when:
    - not _vault_status.initialized
