---
- name: Get vault status
  uri:
    url: "{{ __vault_api_status }}"
    return_content: yes
  register: _current_vault_status
  retries: 10
  delay: 10
  until:
    - _current_vault_status.status == 200

- name: Init if not already done
  when:
    - not _current_vault_status.json.initialized
  block:
    - name: Node initialization
      command: >-
        vault operator init -format json -address={{ __vault_conf_api_addr }}
      register: _vault_init_results

    - name: Store vault init keys
      copy:
        dest: "{{ vault_local_unseal_file }}"
        mode: 0600
        content: |-
          ---
          {{ _vault_init_results.stdout | from_json | to_nice_yaml }}
      become: false
      delegate_to: localhost

    - name: Get vault status
      uri:
        url: "{{ __vault_api_status }}"
        return_content: yes
      register: _current_vault_status
      retries: 10
      delay: 10
      until:
        - _current_vault_status.status == 200
        - _current_vault_status.json.initialized

