---
- name: Load unseal keys
  include_vars:
    file: "{{ vault_local_unseal_file }}"
    name: unseal_keys

- assert:
    that:
      - unseal_keys is defined
      - unseal_keys.recovery_keys_threshold is defined
      - unseal_keys.unseal_keys_b64 is defined
  no_log: yes

- include_tasks: "vault_status.yml"
  when: inventory_hostname in vault_unseal_target

- set_fact:
    _vault_unseal_minimum_keys: >-
      {{ unseal_keys.unseal_keys_b64[:(unseal_keys.recovery_keys_threshold)] }}
  no_log: yes

- block:
    - name: Node unseal one-liner
      shell: >-
        {% set separator = joiner('&&') %}
        {% for unseal_key in _vault_unseal_minimum_keys %}
        {{ separator() }} vault operator unseal
        -address={{ __vault_conf_api_addr }}
        {{ unseal_key }}
        {% endfor %}
      # no_log: yes

    - include_tasks: "vault_status.yml"
  when:
    - inventory_hostname in vault_unseal_target
    - _vault_status.sealed
