---
- name: "Check for terraform module dir"
  stat:
    path: "{{ __hs_stage0_terraform_module_work_dir }}"
  register: _tf_module
  tags:
    - tf

- name: "Do Terraform {{ tf_action }}"
  community.general.terraform:
    project_path: "{{ __hs_stage0_terraform_module_work_dir }}"
    state: "{{ __hs_stage0_state }}"
    force_init: true
    provider_upgrade: true
    workspace: "{{ hs_stage0_name }}"
    variables:
      ssh_public_key_file: "{{ hs_stage0_public_key_file }}"
  register: tf_result
  when: _tf_module.stat.exists
  tags:
    - tf
    - molecule-notest
