---
- name: Host metrics agent
  hosts: "hashistack"
  become: true
  gather_facts: true
  roles:
    - role: "rtnp.galaxie_clans.monitor"

- name: Collect and Present
  hosts: "hashistack_sre"
  become: true
  gather_facts: true
  vars:
    tf_action: "{{ tf_action }}"

  pre_tasks:
    - name: Load group vars
      include_vars:
        dir: "{{ hs_workspace_group_vars_dir }}"
        ignore_unknown_extensions: true

  roles:
    - role: "cloudalchemy.prometheus"
    - role: "grafana"

- name: Define consul services for exporters
  hosts: "hashistack"
  tags:
    - consul
  become: true
  gather_facts: true
  tasks:
    - copy:
        dest: /etc/consul.d/consul.api.json
        content: |-
          {
            "service": {
              "name": "consul_api",
              "tags": [
                "platform"
              ],
              "port": 8501,
              "address": "{{ inventory_hostname }}.{{ public_domain }}"
            }          
          }

    - copy:
        dest: /etc/consul.d/node_exporter.service.json
        content: |-
          {
            "service": {
              "name": "netdata_exporter",
              "tags": [
                "prometheus"
              ],
              "port": 19999,
              "address": "{{ inventory_hostname }}.{{ public_domain }}"
            }          
          }

    - service:
        name: consul
        state: reloaded
